In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/superstore.csv")
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode
0,CA-2019-160304,1/1/2019,7/1/2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,Maryland,East,FUR-BO-10004709,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.94,1,28.2668,No,Online
1,CA-2019-160304,2/1/2019,7/1/2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,Maryland,East,FUR-BO-10004709,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.94,3,38.2668,No,Online
2,CA-2019-160304,2/1/2019,7/1/2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,Maryland,East,TEC-PH-10000455,Technology,Phones,GE 30522EE2,231.98,2,67.2742,No,Cards
3,CA-2019-125206,3/1/2019,5/1/2019,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,California,West,OFF-ST-10003692,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.46,2,28.6150,No,Online
4,US-2019-116365,3/1/2019,8/1/2019,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,Texas,Central,TEC-AC-10002217,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.08,2,-5.2640,No,Online

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5901 entries, 0 to 5900
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       5901 non-null   object
 1   Order Date     5901 non-null   object
 2   Ship Date      5901 non-null   object
 3   Ship Mode      5901 non-null   object
 4   Customer ID    5901 non-null   object
 5   Customer Name  5901 non-null   object
 6   Segment        5901 non-null   object
 7   Country        5901 non-null   object
 8   City           5901 non-null   object
 9   State          5901 non-null   object
 10  Region         5901 non-null   object
 11  Product ID     5901 non-null   object
 12  Category       5901 non-null   object
 13  Sub-Category   5901 non-null   object
 14  Product Name   5901 non-null   object
 15  Sales          5901 non-null   float64
 16  Quantity       5901 non-null   int64
 17  Profit         5901 non-null   float64
 18  Returns        5901 non-null   object
 19  Payment Mode   5901 non-null   object
dtypes: float64(2), int64(1), object(17)
memory usage: 922.2+ KB

In [3]:
df.isnull().sum()

Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Profit           0
Returns          0
Payment Mode     0
dtype: int64

In [4]:
df.duplicated().sum()

0

In [6]:
df["Order Date"] = pd.to_datetime(df["Order Date"], format="%d/%m/%Y")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%d/%m/%Y")

In [7]:
df.dtypes

Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Profit                  float64
Returns                  object
Payment Mode             object
dtype: object

In [8]:
df.columns = (
    df.columns
    .str.lower()
    .str.replace(" ", "_")
)

In [9]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id',
       'customer_name', 'segment', 'country', 'city', 'state', 'region',
       'product_id', 'category', 'sub-category', 'product_name', 'sales',
       'quantity', 'profit', 'returns', 'payment_mode'],
      dtype='object')

In [10]:
df.describe()

             sales     quantity       profit
count  5901.000000  5901.000000  5901.000000
mean    265.345589     3.781901    29.700408
std     474.260645     2.212917   259.589138
min       0.836000     1.000000 -6599.978000
25%      71.976000     2.000000     1.795500
50%     128.648000     3.000000     8.502500
75%     265.170000     5.000000    28.615000
max    9099.930000    14.000000  8399.976000

In [19]:
df.to_csv("../data/processed/sales_clean.csv", index=False)